const database = {
  banner: {
    backgroundColor: "#AB6545",
    filename: "banner.png",
    id: "14",
    width: 700,
    height: 1000,
    slug: "banner",
    sources: [
      {
        filename: "banner.png",
        width: null,
      },
      {
        filename: "banner-wide.png",
        width: 768,
      },
    ],
    title: "Wasteland 2012",
  },
  pictures: [
    {
      backgroundColor: "#332417",
      filename: "alone-in-the-forest",
      id: "1",
      width: 3300,
      height: 4200,
      slug: "alone-in-the-forest",
      thumbnailHeight: 936,
      thumbnailLeft: 1929,
      thumbnailTop: 815,
      thumbnailWidth: 936,
      title: "Alone in the Forest",
    },
    {
      backgroundColor: "#3E2836",
      filename: "animal-spirit-1",
      height: 4050,
      id: "2",
      slug: "animal-spirit-1",
      thumbnailHeight: 995,
      thumbnailLeft: 1155,
      thumbnailTop: 972,
      thumbnailWidth: 995,
      title: "Animal Spirit 1",
      width: 5100,
    },
    {
      backgroundColor: "#CCAC9A",
      filename: "ashen",
      height: 4428,
      id: "3",
      slug: "ashen",
      thumbnailHeight: 1096,
      thumbnailLeft: 1411,
      thumbnailTop: 1103,
      thumbnailWidth: 1096,
      title: "Ashen",
      width: 2700,
    },
    {
      backgroundColor: "#CAE8BE",
      filename: "four-elements",
      height: 1905,
      id: "4",
      slug: "four-elements",
      thumbnailHeight: 741,
      thumbnailLeft: 366,
      thumbnailTop: 208,
      thumbnailWidth: 741,
      title: "Four Elements",
      width: 2413,
    },
    {
      backgroundColor: "#BA5D2D",
      filename: "golden",
      height: 3161,
      id: "16",
      slug: "golden",
      thumbnailHeight: 967,
      thumbnailLeft: 814,
      thumbnailTop: 665,
      thumbnailWidth: 967,
      title: "Golden",
      width: 2216,
    },
    {
      backgroundColor: "#2284E0",
      filename: "jacking-on",
      height: 3304,
      id: "5",
      slug: "jacking-on",
      thumbnailHeight: 888,
      thumbnailLeft: 1130,
      thumbnailTop: 1140,
      thumbnailWidth: 888,
      title: "Jacking On",
      width: 3600,
    },
    {
      backgroundColor: "#73D6FA",
      filename: "pardonne-moi",
      height: 2100,
      id: "6",
      slug: "pardonne-moi",
      thumbnailHeight: 789,
      thumbnailLeft: 343,
      thumbnailTop: 838,
      thumbnailWidth: 789,
      title: "Pardonne Moi",
      width: 1500,
    },
    {
      backgroundColor: "#0C0F17",
      filename: "plavalaguna",
      height: 864,
      id: "7",
      slug: "plavalaguna",
      thumbnailHeight: 558,
      thumbnailLeft: 1,
      thumbnailTop: 0,
      thumbnailWidth: 558,
      title: "Plavalaguna",
      width: 606,
    },
    {
      backgroundColor: "#7A4D3F",
      filename: "seven-deadly-nights-out",
      height: 2705,
      id: "8",
      slug: "seven-deadly-nights-out",
      thumbnailHeight: 879,
      thumbnailLeft: 409,
      thumbnailTop: 710,
      thumbnailWidth: 879,
      title: "7 Deadly Nights Out",
      width: 3596,
    },
    {
      backgroundColor: "#DEE2F1",
      filename: "snow-queen",
      height: 5100,
      id: "9",
      slug: "snow-queen",
      thumbnailHeight: 1039,
      thumbnailLeft: 1019,
      thumbnailTop: 1346,
      thumbnailWidth: 1039,
      title: "Snow Queen",
      width: 3300,
    },
    {
      backgroundColor: "#666576",
      filename: "spellcaster-1",
      height: 4200,
      id: "10",
      slug: "spellcaster-1",
      thumbnailHeight: 1404,
      thumbnailLeft: 865,
      thumbnailTop: 629,
      thumbnailWidth: 1404,
      title: "Spellcaster I",
      width: 3300,
    },
    {
      backgroundColor: "#D7C8C5",
      filename: "spellcaster-2",
      height: 3300,
      id: "11",
      slug: "spellcaster-2",
      thumbnailHeight: 1338,
      thumbnailLeft: 1387,
      thumbnailTop: 169,
      thumbnailWidth: 1338,
      title: "Spellcaster II",
      width: 4200,
    },
    {
      backgroundColor: "#3E3126",
      filename: "the-cage",
      height: 4200,
      id: "12",
      slug: "the-cage",
      thumbnailHeight: 1696,
      thumbnailLeft: 1098,
      thumbnailTop: 273,
      thumbnailWidth: 1696,
      title: "The Cage",
      width: 3360,
    },
    {
      backgroundColor: "#C2A374",
      filename: "violet",
      height: 3600,
      id: "13",
      slug: "violet",
      thumbnailHeight: 972,
      thumbnailLeft: 679,
      thumbnailTop: 313,
      thumbnailWidth: 972,
      title: "Violet",
      width: 2700,
    },
    {
      backgroundColor: "#AB6545",
      filename: "wasteland-weekend-2012",
      height: 6000,
      id: "14",
      slug: "wasteland-weekend-2012",
      thumbnailHeight: 1212,
      thumbnailLeft: 1922,
      thumbnailTop: 2028,
      thumbnailWidth: 1212,
      title: "Wasteland 2012",
      width: 4200,
    },
    {
      backgroundColor: "#F2E7D7",
      filename: "wasteland-weekend-2014",
      height: 1440,
      id: "15",
      slug: "wasteland-weekend-2014",
      thumbnailHeight: 648,
      thumbnailLeft: 25,
      thumbnailTop: 111,
      thumbnailWidth: 648,
      title: "Wasteland 2014",
      width: 1008,
    },
  ],
};

export default database;
